spring:
  datasource:
    url: JDBC_DATABASE_URL
    username: JDBC_DATABASE_USERNAME
    password: JDBC_DATABASE_PASSWORD
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/SpringAppDB
#    username: root
#    password: toor
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true    